# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Long Qian
tagline:          'Long Qian'
description:      'Reality augmented.<br>My personal blog of tech and life.'
url:              http://longqian.me/

author:
  name:           'Long Qian'
  url:            http://longqian.me/

paginate:         5
google_analytics: 'UA-91425204-3'
emailme:          mailto:lqian8@jhu.edu

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/qian256/qian256.github.io/