# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Long Qian
tagline:          'Long Qian'
description:      'Reality augmented.<br>My personal blog of tech and life.'
url:              https://longqian.me/

author:
  name:           'Long Qian'
  url:            https://longqian.me/

paginate:         5
google_analytics: 'UA-91425204-2'
emailme:          mailto:lqian@jhu.edu


github:
  repo:           https://github.com/qian256/qian256.github.io/